repos:
  - repo: local
    hooks:
      - id: go-file-arch
        name: go-file-arch
        entry: go run ./cmd/go-file-arch -config .go-file-arch.yml ./...
        language: system
        pass_filenames: false
        types:
          - go
