package filearch

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCallRuleAcceptsResolvedConfigArgument(t *testing.T) {
	for name, mainSource := range map[string]string{
		"direct": `package main
import (
	loader "example.com/service/loader"
	appconfig "example.com/service/internal/config"
)
func main() { var cfg appconfig.Config; loader.GetConfig(&cfg, ".") }
`,
		"renamed import and variable": `package main
import (
	cfgloader "example.com/service/loader"
	settings "example.com/service/internal/config"
)
func main() { var applicationSettings settings.Config; cfgloader.GetConfig(&applicationSettings, ".") }
`,
		"direct allocation": `package main
import (
	"example.com/service/loader"
	appconfig "example.com/service/internal/config"
)
func main() { loader.GetConfig(new(appconfig.Config), ".") }
`,
	} {
		t.Run(name, func(t *testing.T) {
			if err := runCallRuleFixture(t, mainSource, configLoadCallRule()); err != nil {
				t.Fatalf("Run() error = %v", err)
			}
		})
	}
}

func TestCallRuleRejectsMissingDuplicateAndWrongConfigCalls(t *testing.T) {
	tests := map[string]struct {
		mainSource string
		want       string
	}{
		"missing": {
			mainSource: "package main\nfunc main() {}\n",
			want:       "required call count 1, found 0",
		},
		"duplicate": {
			mainSource: `package main
import (
	"example.com/service/loader"
	appconfig "example.com/service/internal/config"
)
func main() { var cfg appconfig.Config; loader.GetConfig(&cfg, "."); loader.GetConfig(&cfg, ".") }
`,
			want: "required call count 1, found 2",
		},
		"wrong config": {
			mainSource: `package main
import (
	"example.com/service/loader"
	wrong "example.com/service/wrongconfig"
)
func main() { var cfg wrong.Config; loader.GetConfig(&cfg, ".") }
`,
			want: "selected call does not match required arguments",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			err := runCallRuleFixture(t, test.mainSource, configLoadCallRule())
			if err == nil || !strings.Contains(err.Error(), "[application-config-loading]") || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("Run() error = %v, want rule and %q", err, test.want)
			}
		})
	}
}

func TestCallRuleRejectsManagerAppArgumentThroughAlias(t *testing.T) {
	mainSource := `package main
import (
	cfgloader "example.com/service/loader"
	service "example.com/service"
)
func main() { application := service.ExampleManagerApp{}; cfgloader.GetConfig(&application, ".") }
`
	err := runCallRuleFixture(t, mainSource, managerAppDenyCallRule())
	if err == nil || !strings.Contains(err.Error(), "[manager-app-must-not-be-reflected]") {
		t.Fatalf("Run() error = %v, want manager app rule", err)
	}
}

func TestCallRuleUsesFileTemplates(t *testing.T) {
	mainSource := `package main
import (
	"example.com/service/loader"
	service "example.com/service"
)
func main() { app := service.ExampleManagerApp{}; loader.GetConfig(&app, ".") }
`
	rule := `templates:
  command:
    pattern: cmd/{name}.go
    captures: {name: '^[a-z][a-z0-9_]*$'}
callRules:
  - id: template-call
    files: {templates: [command]}
    callee: {package: example.com/service/loader, name: GetConfig}
    deny:
      arguments:
        - position: 0
          type: {nameMatches: ['ManagerApp$'], pointer: true}
    message: template-selected call
`
	err := runCallRuleFixture(t, mainSource, rule)
	if err == nil || !strings.Contains(err.Error(), "[template-call]") {
		t.Fatalf("Run() error = %v, want template call rule", err)
	}
}

func TestCallRuleSelectsGeneratedSource(t *testing.T) {
	mainSource := `// Code generated by fixture. DO NOT EDIT.
package main
import (
	"example.com/service/loader"
	service "example.com/service"
)
func main() { app := service.ExampleManagerApp{}; loader.GetConfig(&app, ".") }
`
	rule := `callRules:
  - id: generated-call
    files: {include: [cmd/main.go], generated: true}
    callee: {package: example.com/service/loader, name: GetConfig}
    deny:
      arguments:
        - position: 0
          type: {nameMatches: ['ManagerApp$'], pointer: true}
    message: generated selected call
`
	err := runCallRuleFixture(t, mainSource, rule)
	if err == nil || !strings.Contains(err.Error(), "[generated-call]") {
		t.Fatalf("Run() error = %v, want generated call rule", err)
	}
}

func runCallRuleFixture(t *testing.T, mainSource, rule string) error {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"go.mod":                    "module example.com/service\n\ngo 1.26.5\n",
		"app.go":                    "package service\ntype ExampleManagerApp struct{}\n",
		"loader/config.go":          "package loader\nfunc GetConfig(any, string) {}\n",
		"internal/config/config.go": "package config\ntype Config struct{}\n",
		"wrongconfig/config.go":     "package wrongconfig\ntype Config struct{}\n",
		"cmd/main.go":               mainSource,
		".architecture.yaml":        "version: 1\n" + rule,
	}
	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return Run(context.Background(), Options{
		ConfigPath: filepath.Join(root, ".architecture.yaml"),
		Workdir:    root,
		Patterns:   []string{"./..."},
	})
}

func configLoadCallRule() string {
	return `callRules:
  - id: application-config-loading
    files: {include: [cmd/main.go]}
    callee: {package: example.com/service/loader, name: GetConfig}
    require:
      arguments:
        - position: 0
          type:
            packageMatches: ['^example\.com/service/internal/config$']
            name: Config
            pointer: true
            typeMatches: ['^\*example\.com/service/internal/config\.Config$']
      count: {equals: 1}
    denyNonMatching: true
    message: load config exactly once
`
}

func managerAppDenyCallRule() string {
	return `callRules:
  - id: manager-app-must-not-be-reflected
    files: {include: ['**/*.go']}
    callee: {package: example.com/service/loader, name: GetConfig}
    deny:
      arguments:
        - position: 0
          type:
            nameMatches: ['ManagerApp$']
            pointer: true
    message: manager app is runtime state
`
}
