package filearch

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
)

func TestPackageVariableRule(t *testing.T) {
	tests := []struct {
		name          string
		declaration   string
		filename      string
		mutation      string
		wantViolation bool
	}{
		{
			name: "assignment", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "func replace(replacement map[string]int) { lookup = replacement }", wantViolation: true,
		},
		{
			name: "index assignment", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "func set(key string, value int) { lookup[key] = value }", wantViolation: true,
		},
		{
			name: "index increment", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "func increment(key string) { lookup[key]++ }", wantViolation: true,
		},
		{
			name: "field assignment", declaration: "var config = struct{ Field int }{}", filename: "mutation.go",
			mutation: "func set(value int) { config.Field = value }", wantViolation: true,
		},
		{
			name: "pointer field assignment", declaration: "var config = &struct{ Field int }{}", filename: "mutation.go",
			mutation: "func set(value int) { (*config).Field = value }", wantViolation: true,
		},
		{
			name: "compound assignment", declaration: "var count = 0", filename: "mutation.go",
			mutation: "func increment() { count += 1 }", wantViolation: true,
		},
		{
			name: "range assignment", declaration: `var lookup = ""`, filename: "mutation.go",
			mutation: "func scan(source map[string]int) { for lookup = range source {} }", wantViolation: true,
		},
		{
			name: "range value assignment", declaration: "var lookup = 0", filename: "mutation.go",
			mutation: "func scan(source []int) { for _, lookup = range source {} }", wantViolation: true,
		},
		{
			name: "initialization and read", declaration: "var lookup = map[string]int{}", filename: "read.go",
			mutation: "func read() int { return lookup[\"key\"] }", wantViolation: false,
		},
		{
			name: "local shadow", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "func mutate() { lookup := map[string]int{}; lookup[\"key\"] = 1 }", wantViolation: false,
		},
		{
			name: "parameter shadow", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "func mutate(lookup map[string]int) { lookup[\"key\"] = 1 }", wantViolation: false,
		},
		{
			name: "test file exempt", declaration: "var lookup = map[string]int{}", filename: "mutation_test.go",
			mutation: "func mutateForTest() { lookup[\"key\"] = 1 }", wantViolation: false,
		},
		{
			name: "generated file exempt", declaration: "var lookup = map[string]int{}", filename: "mutation.go",
			mutation: "// Code generated by fixture. DO NOT EDIT.\npackage fixture\nfunc mutateGenerated() { lookup[\"key\"] = 1 }", wantViolation: false,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, dir, "go.mod", "module example.com/static\n\ngo 1.26\n")
			writeFile(t, dir, ".architecture.yaml", packageVariableRuleConfig)
			writeFile(t, dir, "fixture/constant.go", "package fixture\n"+test.declaration+"\n")
			mutation := test.mutation
			if !strings.Contains(mutation, "package fixture") {
				mutation = "package fixture\n" + mutation + "\n"
			}
			writeFile(t, dir, "fixture/"+test.filename, mutation)

			err := Run(context.Background(), Options{
				ConfigPath: filepath.Join(dir, ".architecture.yaml"),
				Workdir:    dir,
				Patterns:   []string{"./..."},
			})
			if test.wantViolation {
				if err == nil || !strings.Contains(err.Error(), "[static-values]") {
					t.Fatalf("Run() error = %v, want static-values violation", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("Run() error = %v, want pass", err)
			}
		})
	}
}

func TestPackageVariableRuleValidation(t *testing.T) {
	for _, test := range []struct {
		name string
		rule string
		want string
	}{
		{name: "non-var declaration", rule: "    declaration: {kind: const}\n    denyWrites: true", want: "declaration kind must be var"},
		{name: "writes not denied", rule: "    declaration: {kind: var}", want: "denyWrites must be true"},
	} {
		t.Run(test.name, func(t *testing.T) {
			path := writeConfigFixture(t, "version: 1\npackageVariableRules:\n  - id: invalid\n    files: {include: [\"**/constant.go\"]}\n"+test.rule+"\n    message: invalid static value rule\n")
			_, err := LoadConfig(path)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("LoadConfig() error = %v, want %q", err, test.want)
			}
		})
	}
}

func TestPackageVariableRuleIncludesTestWritesByDefault(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "go.mod", "module example.com/static\n\ngo 1.26\n")
	writeFile(t, dir, ".architecture.yaml", `
version: 1
packageVariableRules:
  - id: static-values
    files: {include: ["**/constant.go"]}
    declaration: {kind: var, initialized: true}
    denyWrites: true
    message: static package values cannot be written after initialization
`)
	writeFile(t, dir, "fixture/constant.go", "package fixture\nvar lookup = map[string]int{}\n")
	writeFile(t, dir, "fixture/mutation_test.go", "package fixture\nfunc mutateForTest() { lookup[\"key\"] = 1 }\n")

	err := Run(context.Background(), Options{
		ConfigPath: filepath.Join(dir, ".architecture.yaml"),
		Workdir:    dir,
		Patterns:   []string{"./..."},
	})
	if err == nil || !strings.Contains(err.Error(), "[static-values]") || !strings.Contains(err.Error(), "mutation_test.go") {
		t.Fatalf("Run() error = %v, want test-file static-values violation", err)
	}
}

func TestPackageVariableRuleRejectsInvalidTemplateExpansion(t *testing.T) {
	path := writeConfigFixture(t, `
version: 1
templates:
  domain:
    pattern: "core/{domain}/constant.go"
    captures: {domain: "[a-z]+"}
packageVariableRules:
  - id: invalid-template
    files: {templates: [domain]}
    declaration: {kind: var, name: "{missing}"}
    denyWrites: true
    message: invalid template
`)
	_, err := LoadConfig(path)
	if err == nil || !strings.Contains(err.Error(), "invalid declaration template expansion") {
		t.Fatalf("LoadConfig() error = %v, want invalid declaration template expansion", err)
	}
}

const packageVariableRuleConfig = `
version: 1
packageVariableRules:
  - id: static-values
    files:
      include: ["**/constant.go"]
    writeFiles:
      include: ["**/*.go"]
      exclude: ["**/*_test.go"]
      generated: false
    declaration:
      kind: var
      exported: false
      initialized: true
    denyWrites: true
    message: static package values cannot be written after initialization
`
